name: Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Update submodules
      run: |
        git submodule update --init --recursive
        git submodule foreach git pull origin master

    - name: Generate file table for README
      run: |
        echo "| Name | Link |" > data_files.md
        echo "|------|------|" >> data_files.md
        for file in upstream/data/*; do
          filename=$(basename $file)
          echo "| $filename | https://surge.bojin.co/geosite/$filename |" >> data_files.md
        done

    - name: Generate Index Json
      run: |
        echo "{" > index.json
        for file in upstream/data/*; do
          filename=$(basename $file)
          echo "\"$filename\": \"https://surge.bojin.co/geosite/$filename\"," >> index.json
        done
        sed -i '$ s/,$//' index.json
        echo "}" >> index.json

    - name: Update README
      run: |
        cat README_template.md data_files.md > README.md

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Commit and push if necessary
      run: |
        set -e  # Ensure that the script stops on error
        git add README.md
        git add index.json
        # Check if there are changes to be committed
        if ! git diff --staged --quiet; then
          git commit -m "[auto] Sync with upstream"
          git push
        else
          echo "No changes to commit"
        fi

  update-wechatdns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Update WeChat DNS
        run: |
          cd misc/wechat-dns
          bun init -y
          bun install
          bun run index.ts > wechat-dns.list
      - name: Validate WeChat DNS list
        run: |
          cd misc/wechat-dns
          if ! grep -qE '^(#|IP-CIDR,|DOMAIN-SUFFIX,|$)' wechat-dns.list; then
            echo "Invalid content in wechat-dns.list"
            exit 1
          fi
      - name: Commit and push WeChat DNS changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add misc/wechat-dns/wechat-dns.list
          if ! git diff --staged --quiet; then
            git commit -m "[auto] Update WeChat DNS list"
            git push
          else
            echo "No changes to WeChat DNS list"
          fi