name: Update README with Data Files

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Update submodules
      run: |
        git submodule update --init --recursive
        git submodule foreach git pull origin master

    - name: Generate file table for README
      run: |
        echo "| Name | Link |" > data_files.md
        echo "|------|------|" >> data_files.md
        for file in upstream/data/*; do
          filename=$(basename $file)
          echo "| $filename | https://rulelist.bojin.co/geosite/$filename |" >> data_files.md
        done

    - name: Update README
      run: |
        cat README_template.md data_files.md > README.md

    - name: Commit and push if necessary
      run: |
        set -e  # Ensure that the script stops on error
        git add README.md
        # Check if there are changes to be committed
        if ! git diff --staged --quiet; then
          git commit -m "[auto] Sync with upstream"
          git push
        else
          echo "No changes to commit"
        fi